# Generated by Django 4.2.3 on 2024-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="photo",
        ),
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("partner", "Partner"),
                    ("team", "Team"),
                    ("admin", "Admin"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
